version: '3.7'
services:
  dataorigin:
    container_name: mysql
    hostname: mysql
    image: microdb/testdb:client-test
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: test
    command: >
      --server-id=1
      --default-authentication-plugin=mysql_native_password
      --datadir=/var/lib/mysql
      --log-bin=/var/lib/mysql/mysql-bin.log
      --binlog_do_db=test
      --binlog-format=row
    networks:
      microdb-net:
  publisher:
    image: microdb/publisher:latest
    environment:
      MYSQL_HOST: dataorigin
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_TABLES: test
      NATS_HOST: nats
      NATS_PORT: 4222
      NATS_CLUSTER_ID: nats-cluster
      NATS_CLIENT_ID: publisher-client-test
      PUBLISHER_ID: 1
      DATAORIGIN_CFG: /dataorigin.yaml
    depends_on:
      - dataorigin
      - nats
    networks:
      microdb-net:
  querier:
    image: microdb/querier:latest
    environment:
      MYSQL_HOST: dataorigin
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_TABLE: test
      NATS_HOST: nats
      NATS_PORT: 4222
      NATS_CLUSTER_ID: nats-cluster
      NATS_CLIENT_ID: querier-client-test
      DATAORIGIN_CFG: /dataorigin.yaml
    depends_on:
      - dataorigin
      - nats
    networks:
      microdb-net:
  nats:
    image: nats:2.2.1
    ports:
      - '4222:4222'
      - '8222:8222'
    command: >
      -p=4222
      -m=8222
    networks:
      microdb-net:
  stan:
    image: nats-streaming:0.21.2
    ports:
      - '4222'
      - '8222'
    command: >
      -p=4222
      -m=8222
      -cid=nats-cluster
      -store=file
      -dir=store
      -nats_server=nats://nats:4222
    networks:
      microdb-net:

networks:
  microdb-net:
