// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: microdb.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to TypedValue:
	//	*Value_Varchar
	//	*Value_Integer
	//	*Value_Decimal
	//	*Value_Boolean
	//	*Value_Null
	//	*Value_Timestamp
	TypedValue isValue_TypedValue `protobuf_oneof:"typed_value"`
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microdb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_microdb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_microdb_proto_rawDescGZIP(), []int{0}
}

func (m *Value) GetTypedValue() isValue_TypedValue {
	if m != nil {
		return m.TypedValue
	}
	return nil
}

func (x *Value) GetVarchar() string {
	if x, ok := x.GetTypedValue().(*Value_Varchar); ok {
		return x.Varchar
	}
	return ""
}

func (x *Value) GetInteger() int64 {
	if x, ok := x.GetTypedValue().(*Value_Integer); ok {
		return x.Integer
	}
	return 0
}

func (x *Value) GetDecimal() float32 {
	if x, ok := x.GetTypedValue().(*Value_Decimal); ok {
		return x.Decimal
	}
	return 0
}

func (x *Value) GetBoolean() bool {
	if x, ok := x.GetTypedValue().(*Value_Boolean); ok {
		return x.Boolean
	}
	return false
}

func (x *Value) GetNull() *NullValue {
	if x, ok := x.GetTypedValue().(*Value_Null); ok {
		return x.Null
	}
	return nil
}

func (x *Value) GetTimestamp() *timestamppb.Timestamp {
	if x, ok := x.GetTypedValue().(*Value_Timestamp); ok {
		return x.Timestamp
	}
	return nil
}

type isValue_TypedValue interface {
	isValue_TypedValue()
}

type Value_Varchar struct {
	Varchar string `protobuf:"bytes,1,opt,name=varchar,proto3,oneof"`
}

type Value_Integer struct {
	Integer int64 `protobuf:"varint,2,opt,name=integer,proto3,oneof"`
}

type Value_Decimal struct {
	Decimal float32 `protobuf:"fixed32,3,opt,name=decimal,proto3,oneof"`
}

type Value_Boolean struct {
	Boolean bool `protobuf:"varint,4,opt,name=boolean,proto3,oneof"`
}

type Value_Null struct {
	Null *NullValue `protobuf:"bytes,5,opt,name=null,proto3,oneof"`
}

type Value_Timestamp struct {
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3,oneof"`
}

func (*Value_Varchar) isValue_TypedValue() {}

func (*Value_Integer) isValue_TypedValue() {}

func (*Value_Decimal) isValue_TypedValue() {}

func (*Value_Boolean) isValue_TypedValue() {}

func (*Value_Null) isValue_TypedValue() {}

func (*Value_Timestamp) isValue_TypedValue() {}

type NullValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NullValue) Reset() {
	*x = NullValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microdb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullValue) ProtoMessage() {}

func (x *NullValue) ProtoReflect() protoreflect.Message {
	mi := &file_microdb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullValue.ProtoReflect.Descriptor instead.
func (*NullValue) Descriptor() ([]byte, []int) {
	return file_microdb_proto_rawDescGZIP(), []int{1}
}

type QueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Args  []*Value `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microdb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_microdb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_microdb_proto_rawDescGZIP(), []int{2}
}

func (x *QueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryRequest) GetArgs() []*Value {
	if x != nil {
		return x.Args
	}
	return nil
}

type WriteQueryReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok     bool          `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Msg    string        `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Result *DriverResult `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *WriteQueryReply) Reset() {
	*x = WriteQueryReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microdb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteQueryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteQueryReply) ProtoMessage() {}

func (x *WriteQueryReply) ProtoReflect() protoreflect.Message {
	mi := &file_microdb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteQueryReply.ProtoReflect.Descriptor instead.
func (*WriteQueryReply) Descriptor() ([]byte, []int) {
	return file_microdb_proto_rawDescGZIP(), []int{3}
}

func (x *WriteQueryReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *WriteQueryReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *WriteQueryReply) GetResult() *DriverResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type DriverResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResultLastInsertId int64 `protobuf:"varint,1,opt,name=resultLastInsertId,proto3" json:"resultLastInsertId,omitempty"`
	ResultRowsAffected int64 `protobuf:"varint,2,opt,name=resultRowsAffected,proto3" json:"resultRowsAffected,omitempty"`
}

func (x *DriverResult) Reset() {
	*x = DriverResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microdb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DriverResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverResult) ProtoMessage() {}

func (x *DriverResult) ProtoReflect() protoreflect.Message {
	mi := &file_microdb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverResult.ProtoReflect.Descriptor instead.
func (*DriverResult) Descriptor() ([]byte, []int) {
	return file_microdb_proto_rawDescGZIP(), []int{4}
}

func (x *DriverResult) GetResultLastInsertId() int64 {
	if x != nil {
		return x.ResultLastInsertId
	}
	return 0
}

func (x *DriverResult) GetResultRowsAffected() int64 {
	if x != nil {
		return x.ResultRowsAffected
	}
	return 0
}

type RowUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Row []*Value `protobuf:"bytes,1,rep,name=row,proto3" json:"row,omitempty"`
}

func (x *RowUpdate) Reset() {
	*x = RowUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_microdb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RowUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowUpdate) ProtoMessage() {}

func (x *RowUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_microdb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RowUpdate.ProtoReflect.Descriptor instead.
func (*RowUpdate) Descriptor() ([]byte, []int) {
	return file_microdb_proto_rawDescGZIP(), []int{5}
}

func (x *RowUpdate) GetRow() []*Value {
	if x != nil {
		return x.Row
	}
	return nil
}

var File_microdb_proto protoreflect.FileDescriptor

var file_microdb_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xea, 0x01, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x1a, 0x0a, 0x07, 0x76, 0x61, 0x72, 0x63, 0x68, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x76, 0x61, 0x72, 0x63, 0x68, 0x61, 0x72, 0x12, 0x1a, 0x0a,
	0x07, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00,
	0x52, 0x07, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x07, 0x64, 0x65, 0x63,
	0x69, 0x6d, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x07, 0x64, 0x65,
	0x63, 0x69, 0x6d, 0x61, 0x6c, 0x12, 0x1a, 0x0a, 0x07, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x07, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x61,
	0x6e, 0x12, 0x26, 0x0a, 0x04, 0x6e, 0x75, 0x6c, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x75, 0x6c, 0x6c, 0x12, 0x3a, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x00, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x42, 0x0d, 0x0a, 0x0b, 0x74, 0x79, 0x70, 0x65, 0x64, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x0b, 0x0a, 0x09, 0x4e, 0x75, 0x6c, 0x6c, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x46, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22, 0x60, 0x0a, 0x0f, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02,
	0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x2b,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x6e, 0x0a, 0x0c, 0x44,
	0x72, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2e, 0x0a, 0x12, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x4c, 0x61, 0x73, 0x74, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4c,
	0x61, 0x73, 0x74, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x12, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x6f, 0x77, 0x73, 0x41, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52,
	0x6f, 0x77, 0x73, 0x41, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x22, 0x2b, 0x0a, 0x09, 0x52,
	0x6f, 0x77, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x03, 0x72, 0x6f, 0x77, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_microdb_proto_rawDescOnce sync.Once
	file_microdb_proto_rawDescData = file_microdb_proto_rawDesc
)

func file_microdb_proto_rawDescGZIP() []byte {
	file_microdb_proto_rawDescOnce.Do(func() {
		file_microdb_proto_rawDescData = protoimpl.X.CompressGZIP(file_microdb_proto_rawDescData)
	})
	return file_microdb_proto_rawDescData
}

var file_microdb_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_microdb_proto_goTypes = []interface{}{
	(*Value)(nil),                 // 0: proto.Value
	(*NullValue)(nil),             // 1: proto.NullValue
	(*QueryRequest)(nil),          // 2: proto.QueryRequest
	(*WriteQueryReply)(nil),       // 3: proto.WriteQueryReply
	(*DriverResult)(nil),          // 4: proto.DriverResult
	(*RowUpdate)(nil),             // 5: proto.RowUpdate
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_microdb_proto_depIdxs = []int32{
	1, // 0: proto.Value.null:type_name -> proto.NullValue
	6, // 1: proto.Value.timestamp:type_name -> google.protobuf.Timestamp
	0, // 2: proto.QueryRequest.args:type_name -> proto.Value
	4, // 3: proto.WriteQueryReply.result:type_name -> proto.DriverResult
	0, // 4: proto.RowUpdate.row:type_name -> proto.Value
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_microdb_proto_init() }
func file_microdb_proto_init() {
	if File_microdb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_microdb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microdb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microdb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microdb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteQueryReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microdb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DriverResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_microdb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RowUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_microdb_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Value_Varchar)(nil),
		(*Value_Integer)(nil),
		(*Value_Decimal)(nil),
		(*Value_Boolean)(nil),
		(*Value_Null)(nil),
		(*Value_Timestamp)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_microdb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_microdb_proto_goTypes,
		DependencyIndexes: file_microdb_proto_depIdxs,
		MessageInfos:      file_microdb_proto_msgTypes,
	}.Build()
	File_microdb_proto = out.File
	file_microdb_proto_rawDesc = nil
	file_microdb_proto_goTypes = nil
	file_microdb_proto_depIdxs = nil
}
