before:
  hooks:
    - go mod download
builds:
- id: microdb-publisher
  main: ./cmd/publisher/main.go
  binary: microdb-publisher
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
  goarch:
    - amd64

- id: microdb-querier
  main: ./cmd/querier/main.go
  binary: microdb-querier
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
  goarch:
    - amd64
archives:
- format_overrides:
    - goos: windows
      format: zip
release:
  github:
  prerelease: auto
dockers:
  - goos: linux
    goarch: amd64
    goarm: ''
    image_templates:
    - "microdb/publisher:latest"
    - "microdb/publisher:{{ .Tag }}"
    skip_push: false
    dockerfile: docker/releases/Dockerfile.publisher
    use_buildx: true
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--platform=linux/arm64"

  - goos: linux
    goarch: amd64
    goarm: ''
    image_templates:
    - "microdb/querier:latest"
    - "microdb/querier:{{ .Tag }}"
    skip_push: false
    dockerfile: docker/releases/Dockerfile.querier
    use_buildx: true
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--platform=linux/arm64"
