before:
  hooks:
    - go mod download
builds:
- id: microdb-publisher
  main: ./cmd/publisher/main.go
  binary: microdb-publisher
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
  goarch:
    - amd64
- id: microdb-querier
  main: ./cmd/querier/main.go
  binary: microdb-querier
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
  goarch:
    - amd64
archives:
- format_overrides:
    - goos: windows
      format: zip
release:
  github:
  prerelease: auto
