FROM alpine:latest

LABEL maintainer="Julian Ho <julianho@brandeis.edu>"

RUN apk update && \
    apk add ca-certificates mariadb-client && \
    rm -rf /var/cache/apk/*


COPY microdb-publisher /

ENTRYPOINT ["/microdb-publisher"]
