FROM alpine:3.10

LABEL maintainer="Julian Ho <julianho@brandeis.edu>"

RUN apk update && \
    apk add ca-certificates mariadb-client && \
    rm -rf /var/cache/apk/*

COPY bin/microdb-publisher /
COPY internal/test/test_dataorigin.yaml /dataorigin.yaml

ENTRYPOINT ["/microdb-publisher"]
